#!/bin/bash

function HELP {

        clear
        
        echo "  ____                                                _       "
        echo " / ___| ___   _ __ ___   _ __ ___    __ _  _ __    __| | ___  "
        echo "| |    / _ \ | '_ ' _ \ | '_ ' _ \  / _' || '_ \  / _' |/ __| "
        echo "| |___| (_) || | | | | || | | | | || (_| || | | || (_| |\__ \ "
        echo " \____|\___/ |_| |_| |_||_| |_| |_| \__,_||_| |_| \__,_||___/ "
        echo "──┬────────────────────────────────────────────────────────── "
        echo "  │home = clears the terminal andreturns to the home badge    "
        echo "  ├────────────────────────────────────────────────────────   "
        echo "  │HELP = Gets you here                                       "
        echo "  ├─────────────────────                                      "
        echo "  │netkeychain                                                "
        echo "  └───┬────────────────────────────────                       "
        echo "      │ls = displays all saved servers                        "
        echo "      ├─────────────────────────────────────                  "
        echo "      │add = save a server to your keychain                   "
        echo "  ┌───┴─────────────────────────────────────                  "
        echo "  │server                                                     "
        echo "  └───┬───────────────────────────────────────────────────    "
        echo "      │ssh = connects to an ssh server from your keychain     "
        echo "      ├─────────────────────────────────────────────────────  "
        echo "      │sftp = connects to an sftp server from your keychain   "
        echo "  ┌───┴─────────────────────────────────────────────────────  "
        echo "  |macro                                                      "
        echo "  └───┬─────────────────────────────────────────────          "
        echo "      |create = saves commands to be executed later           "
        echo "      ├─────────────────────────────────────────────          "
        echo "      |leave blank = executes your saved macro                "
        echo "  ┌───┴────────────────────────────────────────               "
        echo "  |lsg                                                        "
        echo "  └───┬─────────────────────────────────────                  "
        echo "      |an ASCII graphical alternative to ls                   "
        echo "      └─────────────────────────────────────                  "
        echo "                                                              "
        echo "  ┌──────────────────────────────────                         "
        echo "  |Prexisting but modified commands:                          "
        echo "  ├──────────────────────────────────                         "
        echo "  |pwd                                                        "
        echo "  └───┬────────────────────────────────────────────────────── "
        echo "      |adds a little bit of text, and colors in the location  "
        echo "  ┌───┴────────────────────────────────────────────────────── "
        echo "  |clear                                                      "
        echo "  └───┬───────────────────────────────────────────────────    "
        echo "      |displays the home badge once the terminal is empty     "
        echo "  ┌───┴───────────────────────────────────────────────────    "
        echo "  |reset                                                      "
        echo "  └───┬───────────────────────────────────────────────────    "
        echo "      |displays the home badge once the terminal is reset     "
        echo "  ┌───┴───────────────────────────────────────────────────    "
        echo "  |mkdir                                                      "
        echo "  └───┬───────────────────────────────────────────────────    "
        echo "      |not only creates a directory, but cd's to it after     "
        echo "      └───────────────────────────────────────────────────    "
    }